import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { ParseService } from '../services/parse.service';
import { SharedModule } from '../shared/shared/shared.module';
import { TaskInterface } from '../interfaces/tasks.interface';
import { SpeechService } from '../services/speech.service';

@Component({
  selector: 'app-tab2',
  standalone: true,
  templateUrl: 'tab2.page.html',
  styleUrls: ['tab2.page.scss'],
  imports: [SharedModule]
})
export class Tab2Page implements OnInit {
  tasks: TaskInterface[] = [];
  inputText: string = '';

  constructor(
    private parseService: ParseService,
    private cdRef: ChangeDetectorRef,
    private speechService: SpeechService) { }

  ngOnInit() {
    this.loadTasks();
  }

  // Load all tasks
  loadTasks() {
    this.parseService.getTasks().subscribe({
      next: tasks => {
        console.log({ tasks });
        this.tasks = tasks;
      },
      error: err => console.error('Error loading tasks:', err)
    });
  }

  // Add a new task with default or input value
  addTask(val: string) {
    if (!this.inputText.trim()) return;

    const newTask: TaskInterface = {
      user: {
        __type: "Pointer",
        className: "_User",
        objectId: "pnD9XLYwGS", // TODO: Replace with actual logged-in user ID
      },
      title: val ?? "New Task",
      description: "Default description",
      priority: 2,
      status: "pending",
    };

    this.parseService.createTask(newTask).subscribe({
      next: (createdTask) => {

        this.tasks = [{ ...createdTask, ...newTask }, ...this.tasks]; // Trigger change detection
        console.log("Task added:", createdTask, this.tasks);
        this.inputText = ''; // Clear Input field
        this.cdRef.detectChanges();
      },
      error: (err) => {
        console.error("Error adding task:", err);
        this.inputText = '';
      }
    });
  }

  // Delete a task
  deleteTask(taskId: string | undefined) {
    if (!taskId) {
      console.warn("Task ID is undefined, skipping delete.");
      return;
    }

    this.parseService.deleteTask(taskId).subscribe({
      next: () => {
        console.log("Task deleted:", taskId);
        this.tasks = this.tasks.filter(task => task.objectId !== taskId);
      },
      error: err => console.error("Error deleting task:", err)
    });
  }

  async readTask(task: string) {
    console.log(`Reading task: ${task}`);
    await this.speechService.speakText(task);
  }

  // Add a task using AI processing
  addTaskWithAI() {
    if (!this.inputText.trim()) return;

    this.parseService.processTextWithAI(this.inputText).subscribe({
      next: taskDetails => {
        const newTask: TaskInterface = {
          user: {
            "__type": "Pointer",
            "className": "_User",
            "objectId": "pnD9XLYwGS"
          },
          title: taskDetails,
          description: 'Generated by AI',
          priority: 1,
          status: 'pending'
        };

        this.parseService.createTask(newTask).subscribe({
          next: createdTask => {
            console.log('AI Task created:', createdTask);
            this.tasks = this.tasks = [{ ...createdTask, ...newTask }, ...this.tasks];
            this.inputText = ''; // Clear input field
            this.cdRef.detectChanges();
          },
          error: err => console.error('Error adding AI task:', err)
        });
      },
      error: err => console.error('Error processing AI:', err)
    });
  }

  // Add a sample task
  addSampleTask() {
    const sampleTask: TaskInterface = {
      user: {
        "__type": "Pointer",
        "className": "_User",
        "objectId": "pnD9XLYwGS"
      },
      title: 'Sample Task',
      description: 'This is a sample task created on button click',
      priority: 1,
      status: 'pending'
    };



    this.parseService.createTask(sampleTask).subscribe({
      next: createdTask => {
        console.log('Sample task created:', createdTask);
        this.tasks.push(createdTask);
      },
      error: err => console.error('Error adding sample task:', err)
    });
  }
}